# [REMOVE] This is just an example, we can change it or remove it

---
# Custom resource definition for RSACracker
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rsacrackers.suu-kopf.dev
spec:
  scope: Namespaced
  group: suu-kopf.dev
  names:
    kind: RSACraker
    plural: rsacrackers
    singular: rsacracker
    shortNames:
      - rsacs
      - rsac
  versions:
    # TODO copied from documentation, should be reviewed
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
