# Deploys the operator's Docker image
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: rsac-operator
  template:
    metadata:
      labels:
        application: rsac-operator
    spec:
      serviceAccountName: kopfexample-account
      volumes:
      - name: tmp-pv-storage
        persistentVolumeClaim:
          claimName: persistent-volume-claim
      containers:
      - name: rsac-operator
        imagePullPolicy: Never # Uncomment this line when developing locally
        image: suukopfproject/rsacracker
        volumeMounts:
          - mountPath: "/usr/share/pvc"
            name: tmp-pv-storage