# Deploys the operator's Docker image
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-deployment
  labels:
    tmp: abcew
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: rsac-operator
  template:
    metadata:
      labels:
        application: rsac-operator
    spec:
      serviceAccountName: kopfexample-account
      volumes:
      - name: main-storage
        persistentVolumeClaim:
          claimName: rsac-persistent-volume-claim
      containers:
      - name: rsac-operator
        imagePullPolicy: Never # Uncomment this line when developing locally
        image: suukopfproject/rsacracker
        volumeMounts:
          - name: main-storage
            mountPath: "/usr/share/pvc"

---

# Service for operator to be achievable from master
apiVersion: v1
kind: Service
metadata:
  name: operator-service
spec:
  type: LoadBalancer
  selector:
    application: rsac-operator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080