---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
