# Service for master to be achievable externally
apiVersion: v1
kind: Service
metadata:
  name: user-master-service
spec:
  type: LoadBalancer
  selector:
    application: master
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080